#!/usr/bin/env sh
# Text Settings
font_family			  monospace
font_size			  10
disable_ligatures     never
scrollback_lines      10000
adjust_line_height    2
close_on_child_death yes

# Cursor Magic
cursor_blink_interval 0

shell_integration no-sudo

tab_bar_style powerline
tab_bar_edge top
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index}  {tab.active_exe} "
tab_bar_min_tabs 1

# SILENCIO!
enable_audio_bell no

# Open new Window (not tab) in same CWD
map ctrl+shift+enter new_window_with_cwd

# asks which tab to move the window into
map ctrl+f4 detach_window ask
# window movement
map ctrl+left neighboring_window left
map ctrl+down neighboring_window down
map ctrl+up neighboring_window up
map ctrl+right neighboring_window right

include ./nord.conf
