#!/usr/bin/env sh
# See dunst(5) for all configuration options

[global]
    alignment = left
    always_run_script = true
    browser = /usr/bin/firefox -new-tab
    class = Dunst
    corner_radius = 5
    ellipsize = end
    monitor = 0
    follow = none
    font = Noto Sans Serif 11
    format = "<b>%a</b>: %s\n%b"
    frame_width = 2
    height = 120
    hide_duplicate_count = false
    history_length = 20
    horizontal_padding = 8
    icon_path = /usr/share/icons/Adwaita/32x32:/usr/share/icons/hicolor/32x32
    icon_position = left
    idle_threshold = 300
    ignore_dbusclose = true
    ignore_newline = false
    indicate_hidden = true
    line_height = 0
    markup = full
    max_icon_size = 32
    min_icon_size = 0
    mouse_left_click = close_current
    mouse_middle_click = do_action, close_current
    mouse_right_click = close_all
    notification_limit = 0
    offset = 10x25
    origin = top-right
    padding = 8
    progress_bar = true
    progress_bar_frame_width = 1
    progress_bar_height = 10
    progress_bar_max_width = 300
    progress_bar_min_width = 150
    scale = 0
    separator_color = frame
    separator_height = 2
    show_age_threshold = -1
    show_indicators = false
    sort = true
    stack_duplicates = true
    sticky_history = true
    text_icon_padding = 5
    title = Dunst
    transparency = 5
    vertical_alignment = center
    width = 300
    word_wrap = true

[urgency_low]
    background = "#3B4252"
    foreground = "#D8DEE9"
    frame_color = "#81A1C1"
    timeout = 10
    # new_icon = /usr/share/icons/Adwaita/24x24/actions/help-about-symbolic.symbolic.png

[urgency_normal]
    background = "#3B4252"
    foreground = "#D8DEE9"
    frame_color = "#8FBCBB"
    timeout = 25
    # new_icon = /usr/share/icons/Adwaita/24x24/status/dialog-information-symbolic.symbolic.png

[urgency_critical]
    background = "#3B4252"
    foreground = "#D8DEE9"
    frame_color = "#BF616A"
    timeout = 20
    # new_icon = /usr/share/icons/Adwaita/24x24/status/dialog-warning-symbolic.symbolic.png
