icons_format = "{icon}"

[icons]
icons = "awesome5"

[theme]
theme = "nord-dark"

[[block]]
block = "cpu"

[[block]]
block = "amd_gpu"
format = " $icon $utilization "
format_alt = " $icon MEM: $vram_used_percents ($vram_used/$vram_total) "

[[block]]
idle = 55
info = 65
warning = 75
block = "temperature"
format = " $icon $average "
chip = "k10temp-*"

[[block]]
block = "memory"
format = " $icon $mem_used.eng(prefix:M,w:4) ($cached.eng(prefix:M,w:4)) / $mem_total.eng(prefix:M,w:4) "

[[block]]
block = "load"
format = " $icon  $1m.eng(w:4), $5m.eng(w:4), $15m.eng(w:4) "
info = 0.6
warning = 0.9
critical = 1.2

[[block]]
block = "sound"
format = " $icon $volume "

[[block]]
block = "music"
format = " $icon {$combo.str(w:30,rot_interval:0.5) $prev $play $next |}"
interface_name_exclude = [".*kdeconnect.*", "mpd"]

[[block]]
block = "net"
format = " $icon  ^icon_net_down $speed_down.eng(prefix:K,w:3) ^icon_net_up $speed_up.eng(prefix:K,w:3) "

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%a, %F %T', l:en_GB) "
interval = 1

[[block]]
block = "github"
format = " $icon $total.eng(w:1) "
info = ["total"]
warning = ["mention","review_requested"]

[[block]]
block = "notify"
