icons = "material-nf"
theme = "nord-dark"

[[block]]
block = "cpu"
format = "{utilization}"
info = 40
interval = 5

[[block]]
block = "temperature"
collapsed = false
interval = 5
idle = 65
info = 90
warning = 95
format = "{average}C"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used} ({cached}) /{mem_total}"
interval = 1

[[block]]
block = "load"
critical = 1.2
format = "{1m}, {5m}, {15m}"
info = 0.6
interval = 5
warning = 0.9

[[block]]
block = "sound"
format = "{volume}"
on_click = "kitty -e alsamixer"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
format = " {combo} "
interface_name_exclude = [".*kdeconnect.*", "mpd"]
max_width = 30
on_collapsed_click = "spotify"

[[block]]
block = "battery"
format = "{percentage}"
driver = "sysfs"
good = 80
info = 50
warning = 30
critical = 15
interval = 5

[[block]]
block = "bluetooth"
mac = "AE:98:0D:4B:EB:A6"
on_click = "blueberry"

[[block]]
block = "networkmanager"
ap_format = "{ssid^10}: {strength}"
device_format = "{icon}{ap}"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
on_click = "kitty -e nmtui"

[[block]]
block = "time"
format = "%a, %T %F"
interval = 1

[[block]]
block = "notify"
